<template>
  <div class="content">
      <!-- <h2>
        分类
      </h2> -->
      <ul >
        <li>lib1</li>
        <li>lib2</li>
        <li>lib3</li>
        <li>lib4</li>
        <li>lib5</li>
        <li>lib6</li>
        <li>lib7</li>
        <li>lib8</li>
        <li>lib9</li>
        <li>lib10</li>
        <li>lib11</li>
        <li>lib12</li>
        <li>lib13</li>
        <li>lib14</li>
        <li>lib15</li>
        <li>lib16</li>
        <li>lib17</li>
        <li>lib18</li>
        <li>lib19</li>
        <li>lib20</li>
        <li>li1</li>
        <li>li2</li>
        <li>li3</li>
        <li>li4</li>
        <li>li5</li>
        <li>li6</li>
        <li>li7</li>
        <li>li8</li>
        <li>li9</li>
        <li>li10</li>
        <li>li11</li>
        <li>li12</li>
        <li>li13</li>
        <li>li14</li>
        <li>li15</li>
        <li>li16</li>
        <li>li17</li>
        <li>li18</li>
        <li>li19</li>
        <li>li20</li>
        <li>li21</li>
        <li>li22</li>
        <li>li23</li>
        <li>li24</li>
        <li>li25</li>
        <li>li26</li>
        <li>li27</li>
        <li>li28</li>
        <li>li29</li>
        <li>li30</li>
        <li>li31</li>
        <li>li32</li>
        <li>li33</li>
        <li>li34</li>
        <li>li35</li>
        <li>li36</li>
        <li>li37</li>
        <li>li38</li>
        <li>li39</li>
        <li>li40</li>
        <li>li41</li>
        <li>li42</li>
        <li>li43</li>
        <li>li44</li>
        <li>li45</li>
        <li>li46</li>
        <li>li47</li>
        <li>li48</li>
        <li>li49</li>
        <li>li50</li>
        <li>li51</li>
        <li>li52</li>
        <li>li53</li>
        <li>li54</li>
        <li>li55</li>
        <li>li56</li>
        <li>li57</li>
        <li>li58</li>
        <li>li59</li>
        <li>li60</li>
        <li>li61</li>
        <li>li62</li>
        <li>li63</li>
        <li>li64</li>
        <li>li65</li>
        <li>li66</li>
        <li>li67</li>
        <li>li68</li>
        <li>li69</li>
        <li>li70</li>
        <li>li71</li>
        <li>li72</li>
        <li>li73</li>
        <li>li74</li>
        <li>li75</li>
        <li>li76</li>
        <li>li77</li>
        <li>li78</li>
        <li>li79</li>
        <li>li80</li>
        <li>li81</li>
        <li>li82</li>
        <li>li83</li>
        <li>li84</li>
        <li>li85</li>
        <li>li86</li>
        <li>li87</li>
        <li>li88</li>
        <li>li89</li>
        <li>li90</li>
        <li>li91</li>
        <li>li92</li>
        <li>li93</li>
        <li>li94</li>
        <li>li95</li>
        <li>li96</li>
        <li>li97</li>
        <li>li98</li>
        <li>li99</li>
        <li>li100</li>
        <li>li101</li>
        <li>li102</li>
        <li>li103</li>
        <li>li104</li>
        <li>li105</li>
        <li>li106</li>
        <li>li107</li>
        <li>li108</li>
        <li>li109</li>
        <li>li110</li>
        <li>li111</li>
        <li>li112</li>
        <li>li113</li>
        <li>li114</li>
        <li>li115</li>
        <li>li116</li>
        <li>li117</li>
        <li>li118</li>
        <li>li119</li>
        <li>li120</li>
        <li>li121</li>
        <li>li122</li>
        <li>li123</li>
        <li>li124</li>
        <li>li125</li>
        <li>li126</li>
        <li>li127</li>
        <li>li128</li>
        <li>li129</li>
        <li>li130</li>
        <li>li131</li>
        <li>li132</li>
        <li>li133</li>
        <li>li134</li>
        <li>li135</li>
        <li>li136</li>
        <li>li137</li>
        <li>li138</li>
        <li>li139</li>
        <li>li140</li>
        <li>li141</li>
        <li>li142</li>
        <li>li143</li>
        <li>li144</li>
        <li>li145</li>
        <li>li146</li>
        <li>li147</li>
        <li>li148</li>
        <li>li149</li>
        <li>li150</li>
        <li>li151</li>
        <li>li152</li>
        <li>li153</li>
        <li>li154</li>
        <li>li155</li>
        <li>li156</li>
        <li>li157</li>
        <li>li158</li>
        <li>li159</li>
        <li>li160</li>
        <li>li161</li>
        <li>li162</li>
        <li>li163</li>
        <li>li164</li>
        <li>li165</li>
        <li>li166</li>
        <li>li167</li>
        <li>li168</li>
        <li>li169</li>
        <li>li170</li>
        <li>li171</li>
        <li>li172</li>
        <li>li173</li>
        <li>li174</li>
        <li>li175</li>
        <li>li176</li>
        <li>li177</li>
        <li>li178</li>
        <li>li179</li>
        <li>li180</li>
        <li>li181</li>
        <li>li182</li>
        <li>li183</li>
        <li>li184</li>
        <li>li185</li>
        <li>li186</li>
        <li>li187</li>
        <li>li188</li>
        <li>li189</li>
        <li>li190</li>
        <li>li191</li>
        <li>li192</li>
        <li>li193</li>
        <li>li194</li>
        <li>li195</li>
        <li>li196</li>
        <li>li197</li>
        <li>li198</li>
        <li>li199</li>
        <li>li200</li>
      </ul>


  </div>
</template>

<script>
import BScroll from 'better-scroll'
export default {
    name:"Category",
    data(){
      return{
        scroll:null
      }
    },
    mounted(){
      this.scroll=new BScroll(document.querySelector('.content'),{
        probeType:3,
        pullUpLoad:true
      })
      this.scroll.on('scroll',(position)=>{
        console.log(position);
      })
      this.scroll.on('pullingUp',()=>{
        // console.log(position);
        console.log("shngrwtstsgsgdgs");
      })
    }
}
</script>
 
<style>
   .content{
    height: 400px;
    background-color: rgb(180, 198, 209);

    overflow:hidden;
  }
</style>